/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "panoply.h"
#include <string.h>
panoply * init_1_svc(panoply *argp, struct svc_req *rqstp)          //initialize the database                                   returns the initialised database
{
	static panoply  result;

    /**/


    /*init abonnements*/
    argp->abonnements.nb_different_abonnement=4;

        /* ~Abonnement n°1~ */
        argp->abonnements.abonnements[0].id_abo = 0;
        strcpy(argp->abonnements.abonnements[0].type_abo,"Un peu");
        argp->abonnements.abonnements[0].prix_abo=69;
        argp->abonnements.abonnements[0].credit_abo=1;

        /* ~Abonnement n°2~ */
        argp->abonnements.abonnements[1].id_abo = 1;
        strcpy(argp->abonnements.abonnements[0].type_abo,"Beaucoup");
        argp->abonnements.abonnements[0].prix_abo=159;
        argp->abonnements.abonnements[0].credit_abo=3;

        /* ~Abonnement n°3~ */
        argp->abonnements.abonnements[2].id_abo = 2;
        strcpy(argp->abonnements.abonnements[0].type_abo,"Passionnément");
        argp->abonnements.abonnements[0].prix_abo=229;
        argp->abonnements.abonnements[0].credit_abo=5;

        /* ~Abonnement n°4~ */
        argp->abonnements.abonnements[3].id_abo = 3;
        strcpy(argp->abonnements.abonnements[0].type_abo,"A la folie");
        argp->abonnements.abonnements[0].prix_abo=319;
        argp->abonnements.abonnements[0].credit_abo=8;

    /*init articles*/
    argp->articles.

    /*init comptes*/
    argp->comptes.nbCompte=1;

        /* ~compte n°1~ */
        argp->comptes.cmpt.id_compte=0;
        strcpy(argp->comptes.cmpt[0].email.email,"client1@univ-brest.fr"); 
        strcpy(argp->comptes.cmpt[0].mdp.mdp,"client1"); 
        strcpy(argp->comptes.cmpt[0].nom,"masse");
        strcpy(argp->comptes.cmpt[0].prenom,"damien");
        argp->comptes.cmpt[0].date_de_naissance.jour = 2;
        argp->comptes.cmpt[0].date_de_naissance.mois = 5;
        argp->comptes.cmpt[0].date_de_naissance.annee = 1975;
        argp->comptes.cmpt[0].telephone = 655482746;
        strcpy(argp->comptes.cmpt[0].profession,"maitre de conf");
        strcpy(argp->comptes.cmpt[0].pays,"france");
        strcpy(argp->comptes.cmpt[0].code_promo,"DS4T56");
        argp->comptes.cmpt[0].connaissance = 1;
        argp->comptes.cmpt[0].abonnement_suivi.abonnements[1]= ;

    /*init collections*/
    argp->collections.

    /*init marques*/
    arpg->marques.

    /*init commandes*/
    arpg->commandes.
    
	return &result;
}

compte * create_account_1_svc(void *argp, struct svc_req *rqstp)    //create an account and add it to the database               returns an account
{
	static compte  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int * log_in_1_svc(identifiants *argp, struct svc_req *rqstp)       /*check if the log in exists                                 returns 0 or -1 if error */
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int * list_all_collection_1_svc(list_collection *argp, struct svc_req *rqstp)   /*display every type of collection                           returns the number of element or -1 if error */
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int * list_all_collection_clothes_1_svc(list_collection *argp, struct svc_req *rqstp)   /*display every clothes for every type of collection         returns the number of clothes or -1 if error */
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

list_collection * add_cloth_to_collection_1_svc(list_collection *argp, struct svc_req *rqstp)   /*add an cloth to a collection                               returns the list of all different collection */
{
	static list_collection  result;

	/*
	 * insert server code here
	 */

	return &result;
}

list_collection * remove_cloth_to_collection_1_svc(list_collection *argp, struct svc_req *rqstp)    /*remove a cloth from a collection                           returns the list of all different collection */
{
	static list_collection  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int * list_type_abo_1_svc(list_abonnement *argp, struct svc_req *rqstp)     /*list every subscription                                    returns the number of element or -1 if error */
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

compte * affecter_abo_client_1_svc(compte *argp, struct svc_req *rqstp)     /*set the subscription of an account                         returns an account */
{
	static compte  result;

	/*
	 * insert server code here
	 */

	return &result;
}

compte * modif_abo_1_svc(compte *argp, struct svc_req *rqstp)           /*edit account subsciption                                   returns 0 or -1 if error */
{
	static compte  result;

	/*
	 * insert server code here
	 */

	return &result;
}

list_abonnement * add_subscription_1_svc(list_abonnement *argp, struct svc_req *rqstp)      /*add a new subscription to the list                         returns a subscription */
{
	static list_abonnement  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int * display_abonnement_1_svc(abonnement *argp, struct svc_req *rqstp)         /*display the number of subscription for every               returns 0 or -1 if error */
{                                                                               /*subscription type 
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

article_list * add_article_1_svc(article_list *argp, struct svc_req *rqstp)     /*add an article to the list of article                     returns the new list of article */
{
	static article_list  result;

	/*
	 * insert server code here
	 */

	return &result;
}

article_list * update_article_1_svc(article_list *argp, struct svc_req *rqstp)      /*update the list of articles                               returns the new list of article */
{
	static article_list  result;

	/*
	 * insert server code here
	 */

	return &result;
}

article_list * delete_article_1_svc(article_list *argp, struct svc_req *rqstp)      /*remove an article from the article list                   returns the new list of article */
{
	static article_list  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int * fetch_article_1_svc(article_list *argp, struct svc_req *rqstp)        /*get a specified article                                   returns 0 or -1 if error */
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int * list_all_brand_1_svc(list_brand *argp, struct svc_req *rqstp)         /*list every brand                                          returns 0 or -1 if error */
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

list_brand * add_brand_1_svc(list_brand *argp, struct svc_req *rqstp)       /*add a brand to the list                                   returns the new list of brand */
{
	static list_brand  result;

	/*
	 * insert server code here
	 */

	return &result;
}

list_brand * delete_brand_1_svc(list_brand *argp, struct svc_req *rqstp)        /*remove a brand from a list                                returns the new list of brand */ 
{
	static list_brand  result;

	/*
	 * insert server code here
	 */

	return &result;
}

list_brand * update_brand_1_svc(list_brand *argp, struct svc_req *rqstp)        /*update a brand from a list                                returns the new list of brand */
{
	static list_brand  result;

	/*
	 * insert server code here
	 */

	return &result;
}

cart * add_to_cart_1_svc(cart *argp, struct svc_req *rqstp)         /*add an article to the cart                                returns the updated cart */
{
	static cart  result;

	/*
	 * insert server code here
	 */

	return &result;
}

cart * rent_1_svc(cart *argp, struct svc_req *rqstp)            /*rent articles from cart                                   returns an empty cart */
{
	static cart  result;

	/*
	 * insert server code here
	 */

	return &result;
}

cart * remove_from_cart_1_svc(cart *argp, struct svc_req *rqstp)        /*remove an article from the cart                           returns the updated cart */
{
	static cart  result;

	/*
	 * insert server code here
	 */

	return &result;
}
