/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "panoply.h"


void
service_panoply_1(char *host)
{
	CLIENT *clnt;
	panoply  *result_1;
	panoply  init_1_arg;
	compte  *result_2;
	char *create_account_1_arg;
	int  *result_3;
	identifiants  log_in_1_arg;
	int  *result_4;
	list_collection  list_all_collection_1_arg;
	int  *result_5;
	list_collection  list_all_collection_clothes_1_arg;
	list_collection  *result_6;
	list_collection  add_cloth_to_collection_1_arg;
	list_collection  *result_7;
	list_collection  remove_cloth_to_collection_1_arg;
	int  *result_8;
	list_abonnement  list_type_abo_1_arg;
	compte  *result_9;
	compte  affecter_abo_client_1_arg;
	compte  *result_10;
	compte  modif_abo_1_arg;
	list_abonnement  *result_11;
	list_abonnement  add_subscription_1_arg;
	int  *result_12;
	abonnement  display_abonnement_1_arg;
	article_list  *result_13;
	article_list  add_article_1_arg;
	article_list  *result_14;
	article_list  update_article_1_arg;
	article_list  *result_15;
	article_list  delete_article_1_arg;
	int  *result_16;
	article_list  fetch_article_1_arg;
	int  *result_17;
	list_brand  list_all_brand_1_arg;
	list_brand  *result_18;
	list_brand  add_brand_1_arg;
	list_brand  *result_19;
	list_brand  delete_brand_1_arg;
	list_brand  *result_20;
	list_brand  update_brand_1_arg;
	void  *result_21;
	cart  list_all_cart_1_arg;
	cart  *result_22;
	cart  add_to_cart_1_arg;
	panoply  *result_23;
	panoply  rent_1_arg;
	cart  *result_24;
	cart  remove_from_cart_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SERVICE_PANOPLY, SERVICE_VERSION_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = init_1(&init_1_arg, clnt);
	if (result_1 == (panoply *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = create_account_1((void*)&create_account_1_arg, clnt);
	if (result_2 == (compte *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = log_in_1(&log_in_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = list_all_collection_1(&list_all_collection_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = list_all_collection_clothes_1(&list_all_collection_clothes_1_arg, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = add_cloth_to_collection_1(&add_cloth_to_collection_1_arg, clnt);
	if (result_6 == (list_collection *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = remove_cloth_to_collection_1(&remove_cloth_to_collection_1_arg, clnt);
	if (result_7 == (list_collection *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = list_type_abo_1(&list_type_abo_1_arg, clnt);
	if (result_8 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = affecter_abo_client_1(&affecter_abo_client_1_arg, clnt);
	if (result_9 == (compte *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_10 = modif_abo_1(&modif_abo_1_arg, clnt);
	if (result_10 == (compte *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_11 = add_subscription_1(&add_subscription_1_arg, clnt);
	if (result_11 == (list_abonnement *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_12 = display_abonnement_1(&display_abonnement_1_arg, clnt);
	if (result_12 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_13 = add_article_1(&add_article_1_arg, clnt);
	if (result_13 == (article_list *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_14 = update_article_1(&update_article_1_arg, clnt);
	if (result_14 == (article_list *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_15 = delete_article_1(&delete_article_1_arg, clnt);
	if (result_15 == (article_list *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_16 = fetch_article_1(&fetch_article_1_arg, clnt);
	if (result_16 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_17 = list_all_brand_1(&list_all_brand_1_arg, clnt);
	if (result_17 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_18 = add_brand_1(&add_brand_1_arg, clnt);
	if (result_18 == (list_brand *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_19 = delete_brand_1(&delete_brand_1_arg, clnt);
	if (result_19 == (list_brand *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_20 = update_brand_1(&update_brand_1_arg, clnt);
	if (result_20 == (list_brand *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_21 = list_all_cart_1(&list_all_cart_1_arg, clnt);
	if (result_21 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_22 = add_to_cart_1(&add_to_cart_1_arg, clnt);
	if (result_22 == (cart *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_23 = rent_1(&rent_1_arg, clnt);
	if (result_23 == (panoply *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_24 = remove_from_cart_1(&remove_from_cart_1_arg, clnt);
	if (result_24 == (cart *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	service_panoply_1 (host);
exit (0);
}
